#!/bin/sh

RUN=$1
FMAX=$2

if [ -z "$1" -o "$1" = "-h" ]; then
  echo Usage: $0 RUN
  exit 0
fi

# RECO = tai, cnr
INPAT=ib"%RECO%NoiseDft"
OUTPAT="dft%RUN%"
if  [ -n "$FMAX" ]; then
  INPAT=$INPAT/ibsetDftFmax$FMAX
  OUTPAT=${OUTPAT}_fmax$FMAX
fi
INPAT="$INPAT/iceberg%RUN%/dftpowtlog_run%RUN%.tpad"
OUTPAT="${OUTPAT}.{png,tpad}"

root.exe -b -q '$DUNENOISE_DIR/root/ibMergeDftPlots.C("'$INPAT'", '$RUN', "'$OUTPAT'")'
